version: "3.9"

services:
  backend:
    container_name: backend
    ports:
     - 8001:8000
    build: .
    restart: unless-stopped
    entrypoint:
      - scripts/entrypoint.sh

  sqs:
     image: roribio16/alpine-sqs:latest
     container_name: sqs
     ports:
       - "9324:9324"
       - "9325:9325"
     stdin_open: true
     tty: true